# Generated by Django 5.2.18 on 2026-10-07 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_orden', models.CharField(max_length=10, unique=True, verbose_name='Código de Orden')),
                ('patente_vehiculo', models.CharField(max_length=8, verbose_name='Patente')),
                ('modelo_vehiculo', models.CharField(max_length=100, verbose_name='Modelo del Vehículo')),
                ('cliente_nombre', models.CharField(max_length=150, verbose_name='Nombre del Cliente')),
                ('costo_estimado', models.IntegerField(verbose_name='Costo Estimado')),
                ('estado', models.CharField(choices=[('INGRESADO', 'Ingresado'), ('EN_PROCESO', 'En Proceso'), ('LISTO', 'Listo'), ('ENTREGADO', 'Entregado')], default='INGRESADO', max_length=20, verbose_name='Estado')),
                ('fecha_ingreso', models.DateField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='taller.especialidad', verbose_name='Especialidad')),
            ],
        ),
    ]
